library/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter

from api.views import BookListViewSet

router = DefaultRouter()
router.register("books", BookListViewSet, "books")

schema_view = get_schema_view(
    openapi.Info(
        title="API документация для проекта Библиотека у дома",
        default_version="v1",
        description="Здесь описаны API для работы с библиотекой у дома.",
        contact=openapi.Contact(email="apic@yandex.ru"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path("", include(router.urls)),
    # path("auth/", include("djoser.urls")),
    path("auth/", include("djoser.urls.authtoken")),
    path(
        "swagger<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

library/books/urls.py
from django.urls import path

from books.views import (
    BooksListView,
    rent_a_book,
    return_a_book,
    MyBooksListView,
    BookCreateView,
    LibrarianDebtorsListView,
)

app_name = "books"

urlpatterns = [
    path("", BooksListView.as_view(), name="index"),
    path("my_books/", MyBooksListView.as_view(), name="my_books"),
    path("rent_a_book/<int:pk>/", rent_a_book, name="rent"),
    path("return_a_book/<int:pk>/", return_a_book, name="return"),
    path("add_book/", BookCreateView.as_view(), name="add_book"),
    path("debtors/", LibrarianDebtorsListView.as_view(), name="debtors"),
]

library/library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls

from core import views


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("books.urls")),
        path("users/", include("users.urls")),
        path("api/", include("api.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + debug_toolbar_urls()
)


handler404 = views.page_not_found

handler500 = views.internal_error

handler403 = views.csrf_failure

library/users/urls.py
from django.urls import include, path

from users.views import SignUpView, UserDetailView, get_dynamic_fields

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("registration/", SignUpView.as_view(), name="registration"),
    path("<slug:username>/", UserDetailView.as_view(), name="profile"),
    path(
        "ajax/get_dynamic_fields/",
        get_dynamic_fields,
        name="get_dynamic_fields",
    ),
]

library/templates/includes/book_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body" id="card-{{ book.pk }}">
      {% if book.cover %}
        <a href="{{ book.cover.url }}" target="_blank">
          <img
              class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block"
              src="{{ book.cover.url }}">
        </a>
      {% endif %}
      <h5 class="card-title" id="card-title">{{ book.title }} </h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {% if book.is_rented %}
            <p class="text-danger">Книга взята на чтение</p>
          {% else %}
            <p class="text-success">Книга доступна!</p>
          {% endif %}
          {{ book.year }} | {{ book.author }} в жанре {{ book.genre }}<br>
        </small>
      </h6>
      {% if not book.is_rented %}
        <form action="{% url "books:rent" book.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-outline-primary">Взять книгу
          </button>
        </form>
      {% elif book.is_rented and book.reader == request.user %}
        <form action="{% url "books:return" book.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary">Вернуть книгу
        </button>
      {% endif %}
      <button class="btn btn-outline-secondary" type="submit" id="copy-button"
              data-toggle="tooltip"
              title="Скопировать">Скопировать название
      </button>
      </form>
    </div>
  </div>
</div>

library/templates/includes/book_data.html
<table>
  <tr>
    <th>Название</th>
    <th>Дата получения книги</th>
    <th>Книга на руках</th>
  </tr>
  <tr>
    <td>{{ book.title|truncatechars:30 }}</td>
    <td>{{ book.rented_at|date }}</td>
    <td>{{ book.rented_at|timesince }}</td>
  </tr>
</table>

library/templates/includes/debtor.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      <h5 class="card-title" id="card-title">{{ debtor.username }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">Полное
        имя: {{ debtor.first_name }} {{ debtor.last_name }}</h6>
      <p class="card-text">Адрес
        проживания: {{ debtor.readerextrafields.address }}</p>
    {% with debtor.books.all as rented_books %}
    {% if rented_books %}
      <p>Книги на руках:</p>
      {% for book in rented_books %}
            <article class="mb-5">
        {% include "includes/book_data.html" %}
            </article>
      {% endfor %}
    {% else %}
      <p><strong>У данного пользователя нет книг на руках</strong></p>
    {% endif %}
    {% endwith %}
    </div>
  </div>
</div>

library/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url "books:index" %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30"
             class="d-inline-block align-top" alt="">
        Библиотека у дома
      </a>
      <ul class="nav nav-pills">
        {% if request.user.is_authenticated %}
          {% if request.user.is_librarian %}
            <div class="btn-group" role="group"
                 aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a
                  class="text-decoration-none text-reset"
                  href="{% url 'books:add_book' %}">Добавить книгу</a></button>
              <button type="button" class="btn btn-outline-primary"><a
                  class="text-decoration-none text-reset"
                  href="{% url 'books:my_books' %}">Мои книги</a></button>
              <button type="button" class="btn btn-outline-primary"><a
                  class="text-decoration-none text-reset"
                  href="{% url 'books:debtors' %}">Должники</a></button>
              <button type="button" class="btn btn-outline-primary"><a
                  class="text-decoration-none text-reset"
                  href="{% url 'users:profile' user.username %}">{{ request.user.username }}</a>
              </button>
              <form action="{% url "users:logout" %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary">Выйти
                </button>
              </form>
            </div>
          {% elif request.user.is_reader %}
            <div class="btn-group" role="group"
                 aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a
                  class="text-decoration-none text-reset"
                  href="{% url 'books:my_books' %}">Мои книги</a></button>
              <button type="button" class="btn btn-outline-primary"><a
                  class="text-decoration-none text-reset"
                  href="{% url 'users:profile' user.username %}">{{ request.user.username }}</a>
              </button>
              <form action="{% url "users:logout" %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary">Выйти
                </button>
              </form>
            </div>
          {% endif %}
        {% else %}
          <div class="btn-group" role="group"
               aria-label="Basic outlined example">
            <button type="button" class="btn btn-outline-primary"><a
                class="text-decoration-none text-reset"
                href="{% url 'users:login' %}">Войти</a></button>
            <button type="button" class="btn btn-outline-primary"><a
                class="text-decoration-none text-reset"
                href="{% url 'users:registration' %}">Регистрация</a></button>
          </div>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>

library/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}